#ifndef StateCode_h
#define StateCode_h

enum class StateCode {
  STATE_SCREEN_OFF,
  STATE_SHOW_TIME,
  STATE_SHOW_DATE,
  STATE_SHOW_SECONDS,
  STATE_SHOW_TEMPERATURE,
  STATE_SHOW_VOLTAGE,
  STATE_SETUP_YEAR,
  STATE_SETUP_MONTH,
  STATE_SETUP_DAY,
  STATE_SETUP_HOURS,
  STATE_SETUP_MINS,
  STATE_SETUP_LUMINOSITY,
  STATE_SETUP_SWITCH_ON_TRANSITION,
  STATE_SETUP_SWITCH_ON_TEXT,
};

#endif
